name: Build and Test Project 1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile copy.c using default GCC
        run: |
          gcc -o copy copy.c

      - name: Prepare test input and run copy
        run: |
          # 원본 파일 생성
          echo "GitHub Actions 테스트 파일" > source.txt
          # copy 실행: source.txt를 복사하여 dest.txt로 생성
          ./copy source.txt dest.txt

      - name: Validate output using diff
        run: |
          diff source.txt dest.txt || { echo 'Copy test failed: source.txt and dest.txt differ'; exit 1; }

      - name: Compile merge.c using default GCC
        run: |
          gcc -o merge merge.c

      - name: Prepare test input and run merge
        run: |
          # 첫 번째 입력 파일 생성
          echo "Hello from file 1" > file1.txt
          # 두 번째 입력 파일 생성
          echo "Hello from file 2" > file2.txt
          # merge 실행: output.txt에 file1.txt와 file2.txt 병합 결과 저장
          ./merge output.txt file1.txt file2.txt

      - name: Validate output using diff
        run: |
          # 두 입력 파일을 순서대로 연결한 expected.txt 파일 생성
          cat file1.txt file2.txt > expected.txt
          # 출력 결과와 expected.txt 파일을 비교, 차이가 있으면 실패
          diff expected.txt output.txt || { echo 'Merge test failed: output.txt does not match expected.txt'; exit 1; }