name: Build and Test copy.c

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile copy.c using default GCC
        run: |
          gcc -o copy copy.c

      - name: Prepare test input and run copy
        run: |
          # 원본 파일 생성
          echo "GitHub Actions 테스트 파일" > source.txt
          # copy 실행: source.txt를 복사하여 dest.txt로 생성
          ./copy source.txt dest.txt

      - name: Validate output using diff
        run: |
          diff source.txt dest.txt